// GENERATED DATA — the parts of the palette a colour direction does not touch.
//
// Status colours and the category palette carry meaning, not brand, so they do
// not rotate with the accent hue. They still differ per THEME (a green that
// works on white is not the green that works on slate), so they are listed per
// theme here and merged into every generated block.
//
// Regenerate with: npm run themes:gen

export const SEMANTIC: Record<string, Record<string, string>> = {
  'light': {
    'cat-din-soft': '#faf5ff',
    'cat-din-text': '#6b21a8',
    'cat-groc-soft': '#fff7ed',
    'cat-groc-text': '#9a3412',
    'cat-house-soft': '#eff6ff',
    'cat-house-text': '#1d4ed8',
    'cat-phone-soft': '#f0f9ff',
    'cat-phone-text': '#075985',
    'cat-rec-soft': '#fdf2f8',
    'cat-rec-text': '#9d174d',
    'cat-sal-soft': '#ecfdf5',
    'cat-sal-text': '#047857',
    'cat-sub-soft': '#eef2ff',
    'cat-sub-text': '#4338ca',
    'cat-tran-soft': '#ecfeff',
    'cat-tran-text': '#155e75',
    'cat-util-soft': '#fffbeb',
    'cat-util-text': '#92400e',
    'cat-xfer-soft': '#f1f5f9',
    'cat-xfer-text': '#475569',
    'state-danger': '#b91c1c',
    'state-danger-soft': '#fee2e2',
    'state-success': '#15803d',
    'state-success-soft': '#dcfce7',
    'state-warning': '#92400e',
    'state-warning-soft': '#fef3c7',
  },
  'light-hc': {
    'cat-din-soft': '#e9d5ff',
    'cat-din-text': '#581c87',
    'cat-groc-soft': '#fed7aa',
    'cat-groc-text': '#7c2d12',
    'cat-house-soft': '#bfdbfe',
    'cat-house-text': '#1e40af',
    'cat-phone-soft': '#bae6fd',
    'cat-phone-text': '#0c4a6e',
    'cat-rec-soft': '#fbcfe8',
    'cat-rec-text': '#831843',
    'cat-sal-soft': '#a7f3d0',
    'cat-sal-text': '#065f46',
    'cat-sub-soft': '#c7d2fe',
    'cat-sub-text': '#3730a3',
    'cat-tran-soft': '#a5f3fc',
    'cat-tran-text': '#164e63',
    'cat-util-soft': '#fde68a',
    'cat-util-text': '#78350f',
    'cat-xfer-soft': '#cbd5e1',
    'cat-xfer-text': '#334155',
    'state-danger': '#991b1b',
    'state-danger-soft': '#fecaca',
    'state-success': '#166534',
    'state-success-soft': '#bbf7d0',
    'state-warning': '#7c2d12',
    'state-warning-soft': '#fde68a',
  },
  'dark': {
    'cat-din-soft': '#3e1c61',
    'cat-din-text': '#d8b4fe',
    'cat-groc-soft': '#3f2912',
    'cat-groc-text': '#fdba74',
    'cat-house-soft': '#162f4b',
    'cat-house-text': '#93c5fd',
    'cat-phone-soft': '#12313f',
    'cat-phone-text': '#7dd3fc',
    'cat-rec-soft': '#511837',
    'cat-rec-text': '#f9a8d4',
    'cat-sal-soft': '#0f3526',
    'cat-sal-text': '#6ee7b7',
    'cat-sub-soft': '#1d2963',
    'cat-sub-text': '#a5b4fc',
    'cat-tran-soft': '#103337',
    'cat-tran-text': '#67e8f9',
    'cat-util-soft': '#372e10',
    'cat-util-text': '#fcd34d',
    'cat-xfer-soft': '#232f3d',
    'cat-xfer-text': '#cbd5e1',
    'state-danger': '#fca5a5',
    'state-danger-soft': '#5d1b1b',
    'state-success': '#4ade80',
    'state-success-soft': '#11391f',
    'state-warning': '#fbbf24',
    'state-warning-soft': '#3d3112',
  },
  'dark-hc': {
    'cat-din-soft': '#291341',
    'cat-din-text': '#d8b4fe',
    'cat-groc-soft': '#2a1b0c',
    'cat-groc-text': '#fdba74',
    'cat-house-soft': '#0e1f31',
    'cat-house-text': '#93c5fd',
    'cat-phone-soft': '#0c202a',
    'cat-phone-text': '#7dd3fc',
    'cat-rec-soft': '#371025',
    'cat-rec-text': '#f9a8d4',
    'cat-sal-soft': '#0a2218',
    'cat-sal-text': '#6ee7b7',
    'cat-sub-soft': '#131b41',
    'cat-sub-text': '#a5b4fc',
    'cat-tran-soft': '#0a2124',
    'cat-tran-text': '#67e8f9',
    'cat-util-soft': '#241e0a',
    'cat-util-text': '#fcd34d',
    'cat-xfer-soft': '#171f28',
    'cat-xfer-text': '#cbd5e1',
    'state-danger': '#f87171',
    'state-danger-soft': '#431414',
    'state-success': '#4ade80',
    'state-success-soft': '#0b2816',
    'state-warning': '#fbbf24',
    'state-warning-soft': '#2b230d',
  },
};
