using Dapper;
using Coffer.Importer.Moneydance.Db;
using Coffer.Importer.Moneydance.Json;
using Coffer.Importer.Moneydance.Pipeline;
using Npgsql;

namespace Coffer.Importer.Moneydance.Tests.Db;

/// <summary>
/// Systemic boundary invariants asserted against a full MD import (roadmap #3 —
/// realistic reference ledger + boundary testing). Rather than checking one
/// narrow behavior, this imports an entire ledger through the real pipeline and
/// asserts the ledger-wide invariants whose violation is exactly the class of
/// bug that slipped past shape-poor unit tests (unbalanced headers from the
/// $1-transfer / self-ref `buysellxfr` defects; holdings drifting from their
/// lots after a recompute).
/// </summary>
/// <remarks>
/// Fixture is <c>data/samples/reference-ledger.json</c> — a synthetic, PII-free
/// QIF-origin export (generated by <c>reference-ledger.gen.mjs</c>) whose shapes
/// were derived by diffing the real import against the demo: blank
/// <c>invest.txntype</c> classified via <c>xfer_type</c> + <c>qif_invst_action</c>
/// (the path 100% of real investment txns use), plus $1-placeholder transfers,
/// a self-ref buysellxfr, security diversity (dec 2–9, money-market / mutual /
/// bond / equity), and an inactive position. The invariant battery is
/// fixture-independent — the reusable vehicle.
/// </remarks>
[Collection(DbCollection.Name)]
public sealed class ReferenceLedgerInvariantsTests
{
    private readonly PostgresFixture _fixture;

    public ReferenceLedgerInvariantsTests(PostgresFixture fixture) => _fixture = fixture;

    [Fact]
    public async Task Full_import_satisfies_systemic_invariants()
    {
        await using var conn = _fixture.OpenConnection();
        await ResetAsync(conn);
        var ledgerId = await ImportReferenceLedgerAsync(conn);

        // Sanity: the fixture actually produced investment holdings to check.
        Assert.True(await conn.ExecuteScalarAsync<int>(
            "SELECT count(*)::int FROM holdings WHERE ledger_id = @L;", new { L = ledgerId }) > 0,
            "reference ledger produced no holdings to assert against");

        // Coverage: the QIF-origin classification (blank invest.txntype → xfer_type +
        // qif_invst_action) must have produced the full action spread, and the
        // fixture must span multiple securities. This fails loudly if a generator
        // edit silently drops a shape (keeping the fixture representative).
        var actions = (await conn.QueryAsync<string>(
            "SELECT DISTINCT action FROM txn_headers WHERE ledger_id = @L AND action IS NOT NULL;",
            new { L = ledgerId })).ToHashSet();
        foreach (var required in new[] { "buy", "sell", "buyx", "sellx", "dividend_cash", "dividend_reinvest", "misc" })
            Assert.True(actions.Contains(required), $"reference ledger missing shape: {required} (have: {string.Join(",", actions)})");
        Assert.True(await conn.ExecuteScalarAsync<int>(
            "SELECT count(*)::int FROM securities WHERE ledger_id = @L;", new { L = ledgerId }) >= 5,
            "reference ledger should span multiple securities");

        // Invariant 1 — double-entry: every non-hidden header's legs sum to zero
        // (ADR-0019 / ADR-0053). The $1-placeholder + self-ref transfer bugs
        // violated this.
        var unbalanced = await conn.QueryAsync<(Guid HeaderId, decimal Sum)>(
            """
            SELECT l.header_id, SUM(l.amount) AS sum
              FROM txn_legs l
              JOIN txn_headers h ON h.id = l.header_id
             WHERE l.ledger_id = @L AND h.is_hidden = FALSE
             GROUP BY l.header_id
            HAVING abs(SUM(l.amount)) > 0.0001;
            """, new { L = ledgerId });
        Assert.True(!unbalanced.Any(),
            "unbalanced headers: " + string.Join(", ", unbalanced.Select(u => $"{u.HeaderId}={u.Sum}")));

        // Invariant 2 — holdings reconcile with their lots: quantity = Σ open-lot
        // quantity and cost_basis = Σ open-lot cost (both split-adjusted by the
        // recompute). A drift here means recompute produced a holding its own
        // lots don't support.
        var drifted = await conn.QueryAsync<(Guid Id, decimal Q, decimal LotQ, decimal CB, decimal LotCB)>(
            """
            SELECT h.id, h.quantity, COALESCE(SUM(l.quantity), 0) AS lot_q,
                   h.cost_basis, COALESCE(SUM(l.quantity * l.unit_cost), 0) AS lot_cb
              FROM holdings h
              LEFT JOIN lots l ON l.holding_id = h.id AND l.is_closed = FALSE
             WHERE h.ledger_id = @L
             GROUP BY h.id, h.quantity, h.cost_basis
            HAVING abs(h.quantity   - COALESCE(SUM(l.quantity), 0)) > 0.0001
                OR abs(h.cost_basis - COALESCE(SUM(l.quantity * l.unit_cost), 0)) > 0.01;
            """, new { L = ledgerId });
        Assert.True(!drifted.Any(),
            "holdings not reconciled with lots: " + string.Join(", ",
                drifted.Select(d => $"{d.Id} qty {d.Q}/{d.LotQ} basis {d.CB}/{d.LotCB}")));

        // Invariant 3 — realized_gains only ever attach to a disposal (a
        // negative-quantity holdings leg), never an acquisition.
        var badRealized = await conn.ExecuteScalarAsync<int>(
            """
            SELECT count(*)::int
              FROM realized_gains rg
              JOIN txn_legs l ON l.id = rg.sell_leg_id
             WHERE rg.ledger_id = @L AND NOT (l.quantity IS NOT NULL AND l.quantity < 0);
            """, new { L = ledgerId });
        Assert.Equal(0, badRealized);

        // Invariant 4 — no holding is left negative (oversold), a classic
        // import-ordering / merge defect.
        Assert.Equal(0, await conn.ExecuteScalarAsync<int>(
            "SELECT count(*)::int FROM holdings WHERE ledger_id = @L AND quantity < -0.0001;",
            new { L = ledgerId }));
    }

    /// <summary>
    /// Import the reference ledger through the real pipeline steps (the path a
    /// live import runs, so import-layer defects surface here).
    /// </summary>
    private static async Task<Guid> ImportReferenceLedgerAsync(NpgsqlConnection conn)
    {
        var ledgerId = await ProvisionLedgerAsync(conn);
        var export = MdItemReader.ReadFile(LocateSampleFile());
        var ctx = new ImportContext(export, ledgerId);
        const string src = "test:reference-ledger.json";

        await SecurityImportStep.RunAsync(conn, ctx);
        await AccountImportStep.RunAsync(conn, ctx);
        await SecuritySplitImportStep.RunAsync(conn, ctx);
        await TransactionImportStep.RunAsync(conn, ctx, src);
        await InvestmentTransactionImportStep.RunAsync(conn, ctx, src);
        await BalanceRecomputeStep.RunAsync(conn, ctx, default);
        return ledgerId;
    }

    private static async Task<Guid> ProvisionLedgerAsync(NpgsqlConnection conn)
    {
        if (await conn.ExecuteScalarAsync<Guid?>("SELECT id FROM ledgers WHERE id=@Id;", new { Id = TestLedger.Id }) is null)
            await conn.ExecuteAsync("INSERT INTO ledgers (id, name) VALUES (@Id,'Default');", new { Id = TestLedger.Id });
        return TestLedger.Id;
    }

    private static Task ResetAsync(NpgsqlConnection conn)
        => conn.ExecuteAsync(@"TRUNCATE security_splits, lots, holdings, realized_gains, security_prices,
             txn_header_account_balances, txn_legs, txn_headers, securities, accounts RESTART IDENTITY CASCADE;");

    private static string LocateSampleFile()
    {
        var cur = new DirectoryInfo(AppContext.BaseDirectory);
        while (cur is not null)
        {
            var p = Path.Combine(cur.FullName, "data", "samples", "reference-ledger.json");
            if (File.Exists(p)) return p;
            cur = cur.Parent;
        }
        throw new FileNotFoundException("Could not locate reference-ledger.json from " + AppContext.BaseDirectory);
    }
}
